-- 1. Tabla para las anotaciones/subrayados
CREATE TABLE public.annotations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  book_id text NOT NULL, -- ID del libro (ej. ID de Google Drive)
  cfi_range text NULL, -- Rango CFI de epub.js para la posición del subrayado
  highlighted_text text NULL, -- El texto subrayado
  color text DEFAULT 'yellow' NOT NULL, -- Color del subrayado
  note_content text NULL -- Contenido de la nota personal
);

-- Comentario para la tabla de anotaciones
COMMENT ON TABLE public.annotations IS 'Almacena subrayados y notas de los libros.';

-- Índice para buscar rápidamente las anotaciones por libro
CREATE INDEX ON public.annotations (book_id);


-- 2. Tabla para las etiquetas (tags)
CREATE TABLE public.tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL UNIQUE
);

-- Comentario para la tabla de etiquetas
COMMENT ON TABLE public.tags IS 'Almacena las etiquetas únicas que se pueden asignar a las anotaciones.';

-- Índice para el nombre del tag
CREATE INDEX ON public.tags (name);


-- 3. Tabla de unión para la relación muchos-a-muchos entre anotaciones y etiquetas
CREATE TABLE public.annotation_tags (
  annotation_id bigint NOT NULL REFERENCES public.annotations(id) ON DELETE CASCADE,
  tag_id bigint NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  PRIMARY KEY (annotation_id, tag_id)
);

-- Comentario para la tabla de unión
COMMENT ON TABLE public.annotation_tags IS 'Relaciona las anotaciones con sus etiquetas.';
